

-- verificando tablespaces existentes

SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;

-- criando tbs

CREATE TABLESPACE TBS_DBAOCM;

CREATE TABLESPACE TBS_DBAOCM DATAFILE '/u02/oradata/my_datafile.dbf' SIZE 10M AUTOEXTEND ON NEXT 512M;

SET LINES 400
COL FILE_NAME FOR A50
SELECT FILE_NAME, BYTES/1024/1024 "TAMANHO MB", AUTOEXTENSIBLE FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='TBS_DBAOCM';


-- setando omf

ALTER SYSTEM SET DB_CREATE_FILE_DEST='/u02/oradata' SCOPE=BOTH;

CREATE TABLESPACE TBS_DBAOCM2;

SET LINES 400
COL FILE_NAME FOR A50
SELECT FILE_NAME, BYTES/1024/1024 "TAMANHO MB", AUTOEXTENSIBLE FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='TBS_DBAOCM2';


!mkdir /u02/multiplex

alter system set db_create_online_log_dest_1='/u02/oradata' scope=both;
alter system set db_create_online_log_dest_2='/u02/multiplex' scope=both;

SHOW PARAMETER db_create_online_log_dest_


!mkdir /u02/oradata/FRA

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/u02/oradata/FRA' SCOPE=BOTH;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE=10G SCOPE=BOTH;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/u02/oradata/FRA' SCOPE=BOTH;

-- adicionando datafile à tablespace 

ALTER TABLESPACE TBS_DBAOCM ADD DATAFILE SIZE 20M;

ALTER TABLESPACE TBS_DBAOCM ADD DATAFILE;

SET LINES 300
COL FILE_NAME FOR A70
COL TABLESPACE_NAME FOR A10
SELECT FILE_NAME, TABLESPACE_NAME, BYTES/1024/1024 MB, AUTOEXTENSIBLE, MAXBYTES/1024/1024 
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='TBS_DBAOCM';

ALTER DATABASE DATAFILE '/u02/oradata/ORCL/datafile/o1_mf_data_l6pwqmwc_.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE 100M;

